language: cpp
sudo: required
dist: trusty

notifications:
  email: false

addons:
  apt:
    sources:
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    update: true
    packages:
    - gcc
    - g++
    - qt510-meta-minimal
    - qt510declarative
    - qt510webengine
    - mesa-common-dev
    - cmake

script:
- export QT_PREFIX=/opt/qt510

- $QT_PREFIX/bin/qt510-env.sh
- export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${QT_PREFIX}/lib"
- export CMAKE_PREFIX_PATH=$QT_PREFIX/lib/cmake
- export QT_SELECT=qt5
- sudo ln -s $QT_PREFIX/bin/qmake /usr/bin/qmake
- bash -xe build_appimages.sh

after_success:
- ls -lh
# make sure only pushes to rewrite create a new release, otherwise pretend PR and upload to transfer.sh
- if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
- wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
- bash upload.sh out/*.AppImage*

branches:
  except:
  - # Do not build tags that we create when we upload to GitHub Releases
  - /^(?i:continuous)$/